// Word Pools for Word Search
window.WordPools = {
  animals: [
    'LEAO', 'TIGRE', 'ELEFANTE', 'GIRAFA', 'MACACO', 'ZEBRA', 'URSO', 'LOBO', 'RAPOSA', 'COELHO',
    'GATO', 'CACHORRO', 'PASSARO', 'PEIXE', 'TUBARAO', 'BALEIA', 'GOLFINHO', 'PINGUIM', 'AGUIA', 'FALCAO',
    'COBRA', 'JACARE', 'SAPO', 'TARTARUGA', 'LAGARTO', 'HIPOPOTAMO', 'RINOCERONTE', 'CANGURU', 'KOALA', 'PANDA'
  ],
  food: [
    'PIZZA', 'HAMBURGUER', 'BATATA', 'ARROZ', 'FEIJAO', 'MACARRAO', 'LASANHA', 'SUSHI', 'SASHIMI', 'TEMAKI',
    'BOLO', 'TORTA', 'SORVETE', 'CHOCOLATE', 'BISCOITO', 'PUDIM', 'BRIGADEIRO', 'BEIJINHO', 'PACOCA', 'COCADA',
    'UVA', 'MACA', 'BANANA', 'LARANJA', 'MORANGO', 'ABACAXI', 'MELANCIA', 'MELAO', 'PERA', 'PESSEGO'
  ],
  sports: [
    'FUTEBOL', 'VOLEI', 'BASQUETE', 'TENIS', 'NATACAO', 'CORRIDA', 'CICLISMO', 'BOXE', 'JUDO', 'KARATE',
    'SURF', 'SKATE', 'GINASTICA', 'ATLETISMO', 'HANDEBOL', 'RUGBY', 'GOLF', 'BASEBOL', 'HOCKEY', 'CRICKET',
    'ESGRIMA', 'REMO', 'VELA', 'CANOAGEM', 'TIRO', 'ARCO', 'HIPISMO', 'TRIATLO', 'BADMINTON', 'SQUASH'
  ],
  nature: [
    'ARVORE', 'FLOR', 'RIO', 'MAR', 'MONTANHA', 'SOL', 'LUA', 'ESTRELA', 'NUVEM', 'CHUVA',
    'VENTO', 'TERRA', 'FOGO', 'AGUA', 'PEDRA', 'AREIA', 'GRAMA', 'FOLHA', 'RAIZ', 'TRONCO',
    'FLORESTA', 'DESERTO', 'ILHA', 'VULCAO', 'CACHOEIRA', 'LAGO', 'OCEANO', 'CEU', 'ARCOIRIS', 'TROVAO'
  ],
  tech: [
    'COMPUTADOR', 'CELULAR', 'TABLET', 'INTERNET', 'WIFI', 'MOUSE', 'TECLADO', 'MONITOR', 'IMPRESSORA', 'SCANNER',
    'ROBO', 'DRONE', 'CAMERA', 'FONE', 'MICROFONE', 'CABO', 'BATERIA', 'TELA', 'CHIP', 'MEMORIA',
    'SOFTWARE', 'HARDWARE', 'VIRUS', 'HACKER', 'CODIGO', 'DADOS', 'REDE', 'SERVER', 'CLOUD', 'APP'
  ]
};
